# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'General Usage'
  link: '/general-usage'
- label: 'Pricing'
  link: '/pricing'
- label: Formatting
  items:
    - label: 'Row Types'
      link: '/formatting/row-types'
    - label: 'Field Information'
      link: '/formatting/field-information'
    - label: 'Spreadsheet'
      link: '/formatting/spreadsheet'
    - label: 'Metafields'
      link: '/formatting/metafields'
    - label: 'Limitations'
      link: '/formatting/limitations'
- label: Other Features
  items:
    - label: 'File Drop'
      link: '/features/file-drop'
    - label: 'Mapping'
      link: '/features/mapping'
    - label: 'Verify Import'
      link: '/features/verify-import'
    - label: 'Invoice Window'
      link: '/features/invoice-window'
    - label: 'Upload Timer'
      link: '/features/upload-timer'
    - label: 'Settings'
      link: '/features/settings'
- label: More
  items:
    - label: FAQ
      link: /faq
    - label: Changelog
      link: /changelog
- label: 'Support'
  items:
    - label: 'Contact Us'
      link: /contact
